<?php $this->headLink()->appendStylesheet('/css/forum.css'); ?>

<h1>Forum</h1>

<?php echo $this->partial('partials/breadcrumb', array(
    'category' => $this->board->getCategory(),
    'board' => $this->board
)); ?>

<h2><?php echo $this->board->getName(); ?></h2>

<?php if (!count($this->board->getTopics())) { ?>
<p>No topics yet. Be the first to <a href="<?php echo $this->url('developers/forum/topic/create', array(
    'board' => $this->board->getId(),
)); ?>">start a topic</a>!</p>
<?php } else { ?>
<p>
    <a href="<?php echo $this->url('developers/forum/topic/create', array(
        'board' => $this->board->getId(),
    )); ?>">start a topic</a>
</p>

<?php echo $this->paginationControl($this->topics, 'Sliding', 'partials/board-pages', array(
    'route' => 'developers/forum/board',
    'board' => $this->board,
)); ?>

<ul>
    <?php foreach ($this->topics as $topic) { ?>
    <li>
        <a href="<?php echo $this->url('developers/forum/topic/read', array(
            'topic' => $topic->getId(),
        )); ?>"><?php echo $topic->getTitle(); ?></a>
    </li>
    <?php } ?>
</ul>

<?php echo $this->paginationControl($this->topics, 'Sliding', 'partials/board-pages', array(
    'route' => 'developers/forum/board',
    'board' => $this->board,
)); ?>

<p>
    <a href="<?php echo $this->url('developers/forum/topic/create', array(
        'board' => $this->board->getId(),
    )); ?>">start a topic</a>
</p>
<?php } ?>