<?php echo $this->headTitle('Pixel Polishers Copyright Policy'); ?>
<?php $this->placeholder('submenu')->exchangeArray(array(
    'www/company/legal/copyright-policy' => 'Copyright Policy',
    'www/company/legal/privacy-policy' => 'Privacy Policy',
    'www/company/legal/terms-of-use' => 'Terms of Use',
)); ?>

<h1>Copyright Policy</h1>

<p>
    Pixel Polishers respects the intellectual property rights of others and expects its users to do
    the same.
</p>

<p>
    It is Pixel Polishers's policy, in appropriate circumstances and at its discretion, to disable
    and/or terminate the account or access of users who repeatedly infringe or are repeatedly
    charged with infringing the copyrights or other intellectual property rights of others.
</p>

<p>
    In accordance with the Digital Millennium Copyright Act of 1998, the text of which may be found
    on the U.S. Copyright Office website at
    <a href="http://www.copyright.gov/legislation/dmca.pdf">http://www.copyright.gov/legislation/dmca.pdf</a>,
    Pixel Polishers will respond expeditiously to claims of copyright infringement committed using
    the Pixel Polishers website (the "Site") that are reported to Pixel Polishers's Designated
    Copyright Agent, identified in the sample notice below.
</p>

<p>
    If you are a copyright owner, or are authorized to act on behalf of one, or authorized to act under any exclusive right under copyright, please report alleged copyright infringements taking place on or through the Site by completing the following DMCA Notice of Alleged Infringement and delivering it to Pixel Polishers's Designated Copyright Agent. Upon receipt of the Notice as described below, Pixel Polishers will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged material from the Site.
</p>

<p>
    DMCA Notice of Alleged Infringement ("Notice")
</p>

<ul>
    <li>
        Identify the copyrighted work that you claim has been infringed, or - if multiple
        copyrighted works are covered by this Notice - you may provide a representative list of the
        copyrighted works that you claim have been infringed.
    </li>
    <li>
        Identify the material that you claim is infringing (or to be the subject of infringing
        activity) and that is to be removed or access to which is to be disabled, and information
        reasonably sufficient to permit us to locate the material, including at a minimum, if
        applicable, the URL of the link shown on the Site where such material may be found.
    </li>
    <li>
        Provide your mailing address, telephone number, and, if available, email address.</li>
    <li>
        Include both of the following statements in the body of the Notice:
        <ul>
            <li>
                "I hereby state that I have a good faith belief that the disputed use of the
                copyrighted material is not authorized by the copyright owner, its agent, or the
                law (e.g., as a fair use)."
            </li>
            <li>
                "I hereby state that the information in this Notice is accurate and, under penalty
                of perjury, that I am the owner, or authorized to act on behalf of the owner, of
                the copyright or of an exclusive right under the copyright that is allegedly
                infringed."
            </li>
        </ul>
    </li>
    <li>Provide your full legal name and your electronic or physical signature.</li>
</ul>

<p>
    Deliver this Notice, with all items completed, to Pixel Polishers's Designated Copyright Agent
    via e-mail at <a href="mailto:legal@pixelpolishers.com">copyright@pixelpolishers.com</a>
</p>

<p style="color: gray; font-size: 0.8em;">
    Last updated:
    <?php echo date('r', filemtime(__FILE__)); ?>
</p>