<?php $this->placeholder('submenu')->exchangeArray(array(
    'company/access/user/overview' => 'Accounts',
    'company/access/role/overview' => 'Roles',
    'company/access/permission/overview' => 'Permissions',
)); ?>

<h2>Newest Users</h2>

<?php if (count($this->latestUsers) == 0) { ?>
<p>No users yet.</p>
<?php } else { ?>
<table>
    <tr>
        <th>ID</th>
        <th>Surname</th>
        <th>Name</th>
        <th>E-mail</th>
    </tr>
    <?php foreach ($this->latestUsers as $user) { ?>
    <tr>
        <td style="text-align: center;"><a href="<?php echo $this->url('company/access/user/view', array(
            'id' => $user->getId(),
        )); ?>"><?php echo $user->getId(); ?></a></td>
        <td><?php echo $user->getSurname(); ?></td>
        <td><?php echo $user->getName(); ?></td>
        <td><a href="mailto:<?php echo $user->getEmail(); ?>"><?php echo $user->getEmail(); ?></a></td>
    </tr>
    <?php } ?>
</table>
<?php } ?>
