<?php $this->headLink()->appendStylesheet('/css/forum.css'); ?>

<h1>Forum</h1>

<?php echo $this->partial('partials/breadcrumb', array(
    'category' => $this->category,
)); ?>

<h2><?php echo $this->category->getName(); ?></h2>

<?php if (count($this->category->getBoards())) { ?>
    <ul>
    <?php foreach ($this->category->getBoards() as $board) { ?>
        <li>
            <h3><a href="<?php echo $this->url('developers/forum/board', array(
                'board' => $board->getId(),
            )); ?>"><?php echo $board->getName(); ?></a></h3>
            <p><?php echo $board->getDescription(); ?></p>
        </li>
    <?php } ?>
    </ul>
<?php } ?>
