<ul>
    <li><a href="<?php echo $this->url('company/index'); ?>">Dashboard</a></li>
    <li><a href="<?php echo $this->url('company/access'); ?>">Access</a></li>
    <li><a href="<?php echo $this->url('company/license'); ?>">Licenses</a></li>
    <li><a href="<?php echo $this->url('developers/index'); ?>">Developers</a></li>
    <li><a href="<?php echo $this->url('account/index'); ?>">Account</a></li>
    <li><a href="<?php echo $this->url('www/index'); ?>">Website</a></li>
</ul>

<?php echo $this->content; ?>