<h1>Pixel Polishers Account</h1>

<p>
    You don't need a Pixel Polishers account to download our software unless you have commercial goals.
    Even though it's still very useful to have a Pixel Polishers account, it gives you access to our
    development environment and store. We like to make things easy for you, just login using your GitHub
    or LinkedIn account and you are ready to go.
</p>

<h2>Sign in</h2>
<?php echo $this->ppSignInForm(); ?>

<h2>Create an account</h2>
<?php echo $this->ppSignUpForm(); ?>
