<?php $this->headLink()->appendStylesheet('/css/forum.css'); ?>

<h1>Forum</h1>

<?php echo $this->partial('partials/breadcrumb', array(
    'category' => $this->topic->getBoard()->getCategory(),
    'board' => $this->topic->getBoard(),
    'topic' => $this->topic,
)); ?>

<h2 id="forum-title"><?php echo $this->topic->getTitle(); ?></h2>

<?php echo $this->partial('partials/topic-nav', array(
    'topic' => $this->topic,
)); ?>

<?php echo $this->paginationControl($this->posts, 'Sliding', 'partials/topic-pages', array(
    'route' => 'developers/forum/topic/read',
    'topic' => $this->topic,
)); ?>

<ul id="topic-posts">
    <?php foreach ($this->posts as $k => $post) { ?>
        <li class="clearfix <?php echo $k % 2 == 0 ? '' : 'odd'; ?>" id="post<?php echo $post->getId(); ?>">
            <div class="meta">
                <a href="<?php echo $this->url('account/view-profile', array(
                    'user' => $post->getCreatedBy()->getId(),
                )); ?>"><?php echo $this->gravatar($post->getCreatedBy()->getEmail()); ?></a>

                <a href="<?php echo $this->url('account/view-profile', array(
                    'user' => $post->getCreatedBy()->getId(),
                )); ?>"><?php echo $post->getCreatedBy()->getDisplayName(); ?></a>
            </div>
            <div class="content">
                <div class="content-body">
                    <?php echo $this->ppForumContent($post->getContent()); ?>
                </div>
                <div class="content-meta">
                    <?php echo $this->ppForumDate($post->getCreatedOn()); ?>
                    |
                    <a href="#post<?php echo $post->getId(); ?>">#<?php echo $post->getId(); ?></a>
                </div>
            </div>
        </li>
    <?php } ?>
</ul>

<?php echo $this->paginationControl($this->posts, 'Sliding', 'partials/topic-pages', array(
    'route' => 'developers/forum/topic/read',
    'topic' => $this->topic,
)); ?>

<?php echo $this->partial('partials/topic-nav', array(
    'topic' => $this->topic,
    'class' => 'footer',
)); ?>
