<?php $this->placeholder('submenu')->exchangeArray(array(
    'company/access/user/overview' => 'Accounts',
    'company/access/role/overview' => 'Roles',
    'company/access/permission/overview' => 'Permissions',
)); ?>

<h2><?php echo $this->user->getDisplayName(); ?></h2>

<p>
    Name: <?php echo $this->user->getName(); ?>
</p>
<p>
    Surname: <?php echo $this->user->getSurname(); ?>
</p>
<p>
    E-mail: <?php echo $this->user->getEmail(); ?>
</p>
<p>
    Registration date: <?php echo $this->user->getRegistrationDate()->format('r'); ?>
</p>
<p>
    Tags: <?php $tags = array(); foreach ($this->user->getTags() as $tag) {
        $tags[] = $tag->getTag();
    } echo $tags ? implode(', ', $tags) : '<em>none</em>'; ?>
</p>
