<?php echo $this->headTitle('Request a new Pixel Polishers password'); ?>

<h1>Request Password</h1>

<?php

$this->form->prepare();

echo $this->form()->openTag($this->form);

echo $this->formLabel($this->form->get('email'));
echo $this->formText($this->form->get('email'));
echo $this->formElementErrors($this->form->get('email'), array('class' => 'errors'));

echo $this->formRow($this->form->get('request'));
echo $this->form()->closeTag($this->form);
