<h1>Documentation</h1>

<ul>
    <li><a href="https://github.com/pixelpolishers/resolver/wiki">Resolver</a></li>
    <li><a href="https://github.com/pixelpolishers/resolver-php-server/wiki">Resolver PHP Server</a></li>
</ul>

<?php /*
<ul class="catalog clearfix">
    <li>
        <a href="<?php echo $this->url('developers/docs/manual', array(
            'project' => 'resolver',
            'version' => 'develop',
            'page' => '',
        )); ?>">Resolver</a>
    </li>
</ul> */