<h2>Delete License</h2>


<p>
    Are you sure you want to delete this license? This is permanent and cannot be reversed.
</p>

<p>
    <?php
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    echo $this->formRow($this->form->get('submit')->setValue('Delete Permantly'));
    echo $this->form()->closeTag();
    ?>
    <a href="<?php echo $this->url('company/access'); ?>">Go back</a>
</p>
