<h2>Licenses</h2>

<?php if (count($this->licenses) == 0) { ?>
<p>No licenses yet. <a href="<?php echo $this->url('company/license/create'); ?>">Create one?</a></p>
<?php } else { ?>
<ul>
<?php foreach ($this->licenses as $license) { ?>
    <li><a href="<?php echo $this->url('company/license/update', array(
        'id' => $license->getId(),
    )); ?>"><?php echo $license->getName(); ?></a></li>
<?php } ?>
</ul>
<?php } ?>
