<h2>Update License: <?php echo $this->license->getName(); ?></h2>

<?php

$this->form->prepare();

echo $this->form()->openTag($this->form);
echo $this->formRow($this->form->get('name'));
echo $this->formRow($this->form->get('description'));
echo $this->formRow($this->form->get('save'));
echo '<a href="' . $this->url('company/license/delete', array(
    'id' => $this->license->getId(),
)) . '">Delete</a>';
echo $this->form()->closeTag();
