<?php echo $this->headTitle($this->user->getDisplayName() . ' at Pixel Polishers'); ?>

<?php $this->placeholder('submenu')->exchangeArray(array(
    'account/index' => 'Dashboard',
    'account/profile' => 'Profile',
    'account/password' => 'Password',
)); ?>

<div class="clearfix">
    <div class="profile-photo">
        <?php echo $this->gravatar($this->user->getEmail(), array(
            'img_size' => 128
        )); ?>
    </div>

    <h1><?php echo $this->user->getDisplayName(); ?></h1>

    <ul>
        <li>A member since <?php echo $this->user->getRegistrationDate()->format('F jS, Y'); ?></li>
    </ul>
</div>
