<?php echo $this->headTitle('Pixel Polishers, the open source game development company'); ?>

<h1>Welcome to Pixel Polishers</h1>

<p>
    Welcome developer. This is the website of Pixel Polishers, the open source game development
    company. We are currently in a startup phase and try to get this website up and running as fast
    as possible. check out our <a href="<?php echo $this->url('developers/index'); ?>">developers portal</a>.
</p>

