<h1>Documentation</h1>

<ul class="catalog clearfix">
    <li>
        <a href="<?php echo $this->url('developers/docs/manual', array(
            'project' => 'resolver',
            'version' => 'develop',
            'page' => '',
        )); ?>">Resolver</a>
    </li>
    <li>
        <a href="<?php echo $this->url('developers/docs/manual', array(
            'project' => 'makedocs',
            'version' => 'develop',
            'page' => '',
        )); ?>">Makedocs</a>
    </li>
</ul>