<h1>Pixel Polishers Account</h1>

<?php if ($this->user) { ?>
<p>
    Display name: <?php echo $this->user->getDisplayName(); ?>
</p>
<p>
    <a href="<?php echo $this->url('account/signout'); ?>">Sign out</a>
</p>
<?php } else { ?>

<p>
    With a Pixel Polishers account you are able to connect to other developers. It becomes possible
    to visit our forums, read our documentation and use the store.
</p>

<h2>Sign in</h2>
<?php echo $this->ppSignInForm(); ?>

<h2>Create an account</h2>
<?php echo $this->ppSignUpForm(); ?>

<?php } ?>