<?php echo $this->headTitle('Pixel Polishers Account'); ?>

<p>
    With a Pixel Polishers account you are able to connect to other developers. It becomes possible
    to visit our forums, read our documentation and use the store.
</p>

<div class="clearfix">
    <div class="left">
        <h2>Sign in</h2>
        <?php echo $this->ppSignInForm(); ?>
    </div>

    <div class="right">
        <h2>Create an account</h2>
        <?php echo $this->ppSignUpForm(); ?>
    </div>
</div>
