<?php $this->placeholder('submenu')->exchangeArray(array(
    'account/index' => 'Dashboard',
    'account/profile' => 'Profile',
    'account/password' => 'Password',
)); ?>

<h1>Change Password</h1>

<?php

$this->form->prepare();

echo $this->form()->openTag($this->form);

echo $this->formLabel($this->form->get('password'));
echo $this->formPassword($this->form->get('password'));
echo $this->formElementErrors($this->form->get('password'), array('class' => 'errors'));

echo $this->formLabel($this->form->get('passwordValidation'));
echo $this->formPassword($this->form->get('passwordValidation'));
echo $this->formElementErrors($this->form->get('passwordValidation'), array('class' => 'errors'));

echo $this->formLabel($this->form->get('currentPassword'));
echo $this->formPassword($this->form->get('currentPassword'));
echo $this->formElementErrors($this->form->get('currentPassword'), array('class' => 'errors'));

echo $this->formRow($this->form->get('save'));
echo $this->form()->closeTag($this->form);
