<!DOCTYPE html>
<html lang="en" dir="ltr" class="no-js">
    <head>
        <?php echo $this->headTitle('Pixel Polishers Account'); ?>

<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="description" content="The open source game development platform." />

        <link rel="shortlink" href="http://pixelpolishers.com/" />
        <link rel="canonical" href="http://pixelpolishers.com/" />

        <link rel="shortcut icon" href="/img/favicons/favicon.ico" />
        <link rel="icon" type="image/png" href="/img/favicons/favicon.png" />

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/favicons/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/favicons/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/favicons/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon-precomposed" href="/img/favicons/apple-touch-icon.png" />

        <link type="text/css" rel="stylesheet" href="/css/screen.css" media="screen" />
        <link type="text/css" rel="stylesheet" href="/css/print.css" media="print" />

        <script type="text/javascript" src="/js/pixelpolishers.js"></script>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-25956726-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

        </script>
    </head>
    <body>

        <ul>
            <li><a href="<?php echo $this->url('www/index'); ?>">Website</a></li>
            <li><a href="<?php echo $this->url('www/index'); ?>">Sign in</a></li>
            <li><a href="<?php echo $this->url('www/index'); ?>">Join</a></li>
        </ul>

        <?php echo $this->content; ?>

    </body>
</html>