<?php $this->placeholder('submenu')->exchangeArray(array(
    'company/access/user/overview' => 'Accounts',
    'company/access/role/overview' => 'Roles',
    'company/access/permission/overview' => 'Permissions',
)); ?>

<h2>Create Permission</h2>

<?php

$this->form->prepare();

echo $this->form()->openTag($this->form);
echo $this->formRow($this->form->get('name'));
echo $this->formRow($this->form->get('save'));
echo $this->form()->closeTag();
