<?php $this->placeholder('submenu')->exchangeArray(array(
    'company/access/user/overview' => 'Accounts',
    'company/access/role/overview' => 'Roles',
    'company/access/permission/overview' => 'Permissions',
)); ?>

<h2>Update Permission</h2>

<p>
    <a href="<?php echo $this->url('company/access/permission/delete', array(
        'id' => $this->permission->getId(),
    )); ?>">Delete Permission</a>
</p>
