<?php $this->headTitle('Pixel Polishers Developers'); ?>

<h1>Developers Dashboard</h1>

<h3>Resolver</h3>

<ul>
    <li><a href="<?php echo $this->url('developers/resolver'); ?>">Search Packages</a></li>
    <li><a href="<?php echo $this->url('developers/resolver/submit'); ?>">Submit Package</a></li>
</ul>

<h3>Documentation</h3>

<ul>
    <li><a href="https://github.com/pixelpolishers/resolver/wiki">Resolver</a></li>
    <li><a href="https://github.com/pixelpolishers/resolver-php-server/wiki">Resolver PHP Server</a></li>
</ul>