<?php echo $this->headTitle('About Pixel Polishers'); ?>
<?php echo $this->headTitle('Pixel Polishers, the open source game development company'); ?>

<h1>About Pixel Polishers</h1>

<p>
    We are Pixel Polishers! An open open source game development company based in the Netherlands.
    We are currently in a
    startup phase and try to get this website up and running as fast as possible. In the mean time,
    check out our <a href="<?php echo $this->url('developers/index'); ?>">developers portal</a>.
</p>

