<?php echo $this->headTitle('Contact Pixel Polishers'); ?>

<h1>Contact us</h1>

<?php if ($this->flashMessenger()->hasErrorMessages()) {
echo '<div class="status error">' . $this->flashMessenger()->render('error') . '</div>';
} ?>

<?php if ($this->flashMessenger()->hasMessages()) {
echo '<div class="status success">' . $this->flashMessenger()->render() . '</div>';
} ?>

<p>
    Since we currently are in a startup phase, we do not have an office yet. Nevertheless you can
    contact us via all social network channels or via de contact form below.
</p>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formLabel($form->get('subject'));
echo $this->formText($form->get('subject'));
echo $this->formElementErrors($form->get('subject'), array('class' => 'errors'));

echo $this->formLabel($form->get('name'));
echo $this->formText($form->get('name'));
echo $this->formElementErrors($form->get('name'), array('class' => 'errors'));

echo $this->formLabel($form->get('email'));
echo $this->formText($form->get('email'));
echo $this->formElementErrors($form->get('email'), array('class' => 'errors'));

echo $this->formLabel($form->get('message'));
echo $this->formTextarea($form->get('message'));
echo $this->formElementErrors($form->get('message'), array('class' => 'errors'));

echo $this->formSubmit($form->get('send'));

echo $this->form()->closeTag();
