<?php echo $this->headTitle('About this website | Pixel Polishers'); ?>

<h1>About this website</h1>
<p>
    This website is managed by Pixel Polisher's internal web development team.
</p>

<h2>Source</h2>
<p>
    As with all our products also this website is fully open source. The source code is located on
    <a href="https://github.com/pixelpolishers/pixelpolishers.com">Github</a>.<br />
    <a href="http://pixelpolishers.com">pixelpolishers.com</a> is made using
    <a href="http://framework.zend.com">Zend Framework 2</a> and
    <a href="http://www.doctrine-project.org">Doctrine ORM</a>. For more information
    and the documentation, please visit the documentation section on our
    <a href="<?php echo $this->url('developers/index'); ?>">developers portal</a>.
</p>

<h2>Questions and comments</h2>
<p>
    Please use the <a href="<?php echo $this->url('www/company/contact'); ?>">contact form</a> to contact us with any
    questions or comments.
</p>
