<h2>Delete Role</h2>


<p>
    Are you sure you want to delete this role? People that have this role assigned will lose access
    to certain parts of the website.
</p>

<p>
    <?php
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    echo $this->formRow($this->form->get('submit')->setValue('Delete Permantly'));
    echo $this->form()->closeTag();
    ?>
    <a href="<?php echo $this->url('company/access'); ?>">Go back</a>
</p>
