<?php

$items = array();

if ($this->ppForumCanCreateTopic($this->board)) {
    $url = $this->url('developers/forum/topic/create', array(
        'board' => $this->board->getId(),
    ));

    $items[$url] = 'Start Topic';
}

?>
<nav class="forum-nav clearfix <?php echo $this->class; ?>">
    <?php if (count($items) != 0) { ?>
    <ul>
        <?php foreach ($items as $url => $label) { ?>
        <li><a href="<?php echo $url; ?>"><?php echo $label; ?></a></li>
        <?php } ?>
    </ul>
    <?php } ?>
</nav>
