<?php if ($this->pageCount) { ?>
    <div class="topic-paginator clearfix">
        <?php if ($this->previous) { ?>
        <div class="item"><a href="<?php echo $this->url($this->route, array(
            'topic' => $this->topic->getId(),
            'page' => $this->previous,
        )); ?>">&lt;</a></div>
        <?php } ?>

        <ol>
            <?php foreach ($this->pagesInRange as $page) { ?>
                <?php if ($page == $this->current) { ?>
                    <li class="item current"><span><?php echo $page; ?></span></li>
                <?php } else { ?>
                    <li class="item"><a href="<?php echo $this->url($this->route, array(
                        'topic' => $this->topic->getId(),
                        'page' => $page,
                    )); ?>"><?php echo $page; ?></a></li>
                <?php } ?>
            <?php } ?>
        </ol>

        <?php if ($this->next) { ?>
        <div class="item"><a href="<?php echo $this->url($this->route, array(
            'topic' => $this->topic->getId(),
            'page' => $this->next,
        )); ?>">&gt;</a></div>
        <?php } ?>
    </div>
<?php } ?>
