<?php

$this->headTitle('Version "' . $this->version->getVersion() . '" deleted');
$this->headLink()->appendStylesheet('/css/resolver.css');
$this->headMeta()->appendHttpEquiv('Refresh', '2;URL=/resolver/package/' . $this->version->getPackage()->getFullname());

$this->placeholder('submenu')->exchangeArray(array(
    'developers/resolver' => 'Search',
    'developers/resolver/submit' => 'Submit',
));

?>

<div style="position: relative">
    <h1><?php echo $this->version->getVersion(); ?> Deleted</h1>

    <p>The version has been deleted.</p>
</div>