<?php

$this->headTitle('Submit a Resolver package - Pixel Polishers Developers');
$this->headScript()->appendFile($this->basePath('/js/URI.js'));
$this->headScript()->appendFile($this->basePath('/js/resolver.js'));
$this->headLink()->appendStylesheet('/css/resolver.css');

$this->placeholder('submenu')->exchangeArray(array(
    'developers/resolver' => 'Search',
    'developers/resolver/submit' => 'Submit',
));

?>

<div style="position: relative">
    <h1>Submit Resolver Package</h1>

    <form action="" method="post">
        <input type="text" name="resolver-url" id="resolver-url" value="" placeholder="http://" class="wide-input" />

        <div id="resolver-status" style="color: red;"></div>

        <div class="package-row" style="display: none;">
            <h3>title</h3>
            <p>description</p>
        </div>

        <div style="text-align: center;">
            <input type="submit" name="resolver-lookup" id="resolver-lookup" value="Lookup" />
            <input type="submit" name="resolver-submit" id="resolver-submit" value="Submit" />
        </div>
    </form>
</div>