<?php

$this->headTitle('Resolver package "' . $this->package->getFullname() . '"');
$this->headLink()->appendStylesheet('/css/resolver.css');

?>

<div style="position: relative">
    <h1><a href="<?php echo $this->package->getRepositoryUrl(); ?>" target="_blank"><?php echo $this->package->getFullname(); ?></a></h1>

    <?php if ($this->owningPackage) { ?>
    <div>
        <ul>
            <li><a href="<?php echo $this->url('developers/resolver/force-update', array(
                'vendor' => $this->package->getVendor()->getName(),
                'name' => $this->package->getName(),
            )); ?>">Force Update</a></li>
            <li><a href="<?php echo $this->url('developers/resolver/delete', array(
                'vendor' => $this->package->getVendor()->getName(),
                'name' => $this->package->getName(),
            )); ?>">Delete</a></li>
        </ul>
    </div>
    <?php } ?>

    <?php
    foreach ($this->sortedVersions as $version) { ?>
    <div class="package-version-row">
        <?php

        $displayVersion = \PixelPolishers\Resolver\SemanticVersion::fromString($version->getVersion());
        $displayVersion = $displayVersion == null ? $version->getVersion() : $displayVersion;

        ?>

        <h3><?php echo $displayVersion; ?></h3>

        <?php if ($this->owningPackage) { ?>
        <div class="package-version-buttons">
            <a href="<?php echo $this->url('developers/resolver/delete-version', array(
                'vendor' => $this->package->getVendor()->getName(),
                'name' => $this->package->getName(),
                'version' => $version->getVersion(),
            )); ?>">delete</a>
        </div>
        <?php } ?>

        <p>
            <pre><?php echo $version->getReferenceHash(); ?></pre>
            <pre>"<?php echo $this->package->getFullname(); ?>": "<?php echo $displayVersion; ?>"</pre>
        </p>
    </div>
    <?php } ?>
</div>