<?php

$this->headTitle('Resolver package "' . $this->package->getFullname() . '"');
$this->headLink()->appendStylesheet('/css/resolver.css');

$this->placeholder('submenu')->exchangeArray(array(
    'developers/resolver' => 'Search',
    'developers/resolver/submit' => 'Submit',
));

?>

<div style="position: relative">
    <h1>
        <a href="<?php echo $this->url('developers/resolver/vendor', array(
            'name' => $this->package->getVendor()->getName(),
        )); ?>">
            <?php echo $this->package->getVendor()->getName(); ?>
        </a>
        /
        <a href="<?php echo $this->package->getRepositoryUrl(); ?>" target="_blank">
            <?php echo $this->package->getName(); ?>
        </a>
    </h1>

    <p><?php echo strip_tags($this->package->getDescription()); ?></p>

    <?php if ($this->owningPackage) { ?>
    <div id="resolver-menu">
        <ul>
            <li><a href="<?php echo $this->url('developers/resolver/force-update', array(
                'vendor' => $this->package->getVendor()->getName(),
                'name' => $this->package->getName(),
            )); ?>">Force Update</a></li>
            <li><a class="delete" href="<?php echo $this->url('developers/resolver/delete', array(
                'vendor' => $this->package->getVendor()->getName(),
                'name' => $this->package->getName(),
            )); ?>">Delete</a></li>
        </ul>
    </div>
    <?php } ?>

    <?php
    foreach ($this->sortedVersions as $version) { ?>
    <div class="package-version-row">
        <?php

        $displayVersion = \PixelPolishers\Resolver\SemanticVersion::fromString($version->getVersion());
        $displayVersion = $displayVersion == null ? $version->getVersion() : $displayVersion;

        ?>

        <h3><?php echo $displayVersion; ?></h3>

        <div class="package-version-buttons">
            <span title="License"><?php echo strip_tags($version->getLicense()); ?></span>
            <?php echo $this->ppResolverReferenceButton($version); ?>
            <?php if ($this->owningPackage) { ?>
            <a class="delete" href="<?php echo $this->url('developers/resolver/delete-version', array(
                'vendor' => $this->package->getVendor()->getName(),
                'name' => $this->package->getName(),
                'version' => $version->getVersion(),
            )); ?>">delete</a>
            <?php } ?>
        </div>

        <p>
            <pre>"<?php echo $this->package->getFullname(); ?>": "<?php echo $displayVersion; ?>"</pre>
        </p>
    </div>
    <?php } ?>
</div>