<?php

echo '<h1>' . $this->message . '</h1>' . PHP_EOL . PHP_EOL;

if (isset($this->display_exceptions) && $this->display_exceptions &&
    isset($this->exception) && $this->exception instanceof \Exception) {

    function displayException($e, $displayPrevious)
    {
        if (!$e) {
            return;
        }

        echo '<div style="border: 1px solid #CCC; background-color: #F9F9F9; margin-bottom: 10px; padding: 10px;">';
        echo '<h3>' . get_class($e) . '</h3>' . PHP_EOL . PHP_EOL;

        echo '<strong>File:</strong>';
        echo '<pre>' . $e->getFile() . ':' . $e->getLine() . '</pre>' . PHP_EOL;

        echo '<strong>Message:</strong>';
        echo '<pre>' . $e->getMessage() . '</pre>' . PHP_EOL;

        echo '<strong>Stack trace:</strong>';
        echo '<pre style="overflow: auto;">' . $e->getTraceAsString() . '</pre>' . PHP_EOL;

        echo '</div>';

        if ($displayPrevious) {
            displayException($e->getPrevious(), true);
        }
    }

    echo '<h2>Additional information:</h2>' . PHP_EOL . PHP_EOL;
    displayException($this->exception, false);

    if ($this->exception->getPrevious()) {
        echo '<h2>Previous exceptions:</h2>';
        displayException($this->exception->getPrevious(), true);
    }
}
